name: staffapp
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^6.0.13


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  adhara_socket_io: ^0.4.1

  http: ^0.12.0+4


flutter:

  uses-material-design: true


